version: 2
updates:
  - package-ecosystem: "uv"
    directory: "project1"
    schedule:
      interval: "daily"
  - package-ecosystem: "uv"
    directory: "project2"
    schedule:
      interval: "daily"
